/**
 * All API input validation lives here. Routes must parse their input through these schemas.
 */
import { z } from "zod";

export const sourceTypeSchema = z.enum(["policy", "manual", "checklist", "email", "teams_chat", "workflow"]);

const shortText = z.string().trim().max(200);

export const searchBriefSchema = z.object({
  question: z.string().trim().min(1).max(500),
  topic_tags: z.array(shortText.min(1).max(40)).max(20),
  scope: z.object({
    country: shortText.max(10).optional(),
    client: shortText.max(80).optional(),
    employee_category: shortText.max(80).optional(),
  }),
  reference_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD"),
  source_types: z.array(sourceTypeSchema).max(6).optional(),
});

export const documentRecordSchema = z.object({
  id: z.string(),
  source_type: sourceTypeSchema,
  title: z.string(),
  url: z.string(),
  summary: z.string(),
  claims: z.array(z.object({ key: z.string(), value: z.string(), unit: z.string().optional() })),
  topic_tags: z.array(z.string()),
  scope: z.object({
    country: z.string().optional(),
    client: z.string().nullable().optional(),
    employee_category: z.string().nullable().optional(),
  }),
  effective_from: z.string().optional(),
  effective_until: z.string().nullable().optional(),
  last_modified: z.string(),
  last_reviewed: z.string().optional(),
  owner: z.object({ name: z.string(), role: z.string(), active: z.boolean() }),
  authority_level: z.number().min(0).max(1),
  supersedes: z.array(z.string()).optional(),
  endorsements: z.number().optional(),
  excerpt: z.string(),
});

export const corpusSchema = z.array(documentRecordSchema);

/** Clarifying answers chosen via quick-reply chips. */
export const clarifySchema = z.object({
  country: shortText.max(10).optional(),
  client: shortText.max(80).optional(),
});

const chatTextSchema = z.string().max(4000);

/** Minimal transcript sent to /api/brief. */
export const briefRequestSchema = z.object({
  messages: z
    .array(z.object({ role: z.enum(["user", "assistant"]), text: chatTextSchema }))
    .min(1)
    .max(30),
  clarify: clarifySchema.default({}),
  reference_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
});

/** /api/chat receives AI SDK UI messages; we only validate the shape we use. */
export const chatRequestSchema = z.object({
  messages: z
    .array(
      z
        .object({
          id: z.string().max(100),
          role: z.enum(["user", "assistant", "system"]),
          parts: z.array(z.object({ type: z.string().max(50), text: chatTextSchema.optional() }).passthrough()).max(50),
        })
        .passthrough(),
    )
    .min(1)
    .max(30),
});

/** Brief generated by the LLM (subset of SearchBrief without reference_date). */
export const llmBriefSchema = z.object({
  question: z.string().describe("The consultant's question, restated clearly in one sentence"),
  topic_tags: z.array(z.string()).describe("3-6 lowercase keywords, e.g. payroll, deadline, december, year-end"),
  country: z.string().optional().describe("ISO country code, e.g. BE or NL"),
  client: z.string().optional().describe("Client name if one was mentioned, otherwise omit"),
});

export type BriefRequest = z.infer<typeof briefRequestSchema>;
export type LlmBrief = z.infer<typeof llmBriefSchema>;
